import 'dart:convert';
import 'dart:io';
import 'dart:math';

import 'package:path/path.dart' as p;

import '../models/discovered_preview.dart';

enum GeneratedHarnessMode { discover, capture }

/// A throwaway code-gen workspace under the project's `.dart_tool/`.
///
/// It holds a generated *registry* (which imports the user's preview libraries
/// unprefixed and re-emits each annotation verbatim) plus a generated
/// `flutter test` harness — either a discovery pass (emits `previews.json`) or a
/// capture pass (also writes one PNG per preview). Everything is deleted via
/// [delete] once the run completes.
class GeneratedWorkspace {
  GeneratedWorkspace._({
    required this.rootDirectory,
    required this.registryFile,
    required this.harnessFile,
    required this.metadataFile,
  });

  final Directory rootDirectory;
  final File registryFile;
  final File harnessFile;
  final File metadataFile;

  static Future<GeneratedWorkspace> create({
    required String projectPath,
    required String packageName,
    required List<DiscoveredPreviewTarget> targets,
    required GeneratedHarnessMode mode,
    required double dpr,
    required String? outputDirectory,
  }) async {
    final token =
        '${DateTime.now().microsecondsSinceEpoch}_${Random().nextInt(1 << 32)}';
    final root = Directory(
      p.join(projectPath, '.dart_tool', 'ambient_flutter', token),
    );
    await root.create(recursive: true);

    final registryFile = File(
      p.join(root.path, 'ambient_preview_registry.dart'),
    );
    final harnessFile = File(
      p.join(
        root.path,
        mode == GeneratedHarnessMode.discover
            ? 'ambient_discovery_test.dart'
            : 'ambient_capture_test.dart',
      ),
    );
    final metadataFile = File(p.join(root.path, 'previews.json'));

    await registryFile.writeAsString(
      _registrySource(packageName: packageName, targets: targets),
    );
    await harnessFile.writeAsString(switch (mode) {
      GeneratedHarnessMode.discover => _discoveryHarnessSource(
        registryImport: p.basename(registryFile.path),
        metadataFile: metadataFile.path,
        dpr: dpr,
      ),
      GeneratedHarnessMode.capture => _captureHarnessSource(
        registryImport: p.basename(registryFile.path),
        metadataFile: metadataFile.path,
        outputDirectory: outputDirectory!,
        dpr: dpr,
      ),
    });

    return GeneratedWorkspace._(
      rootDirectory: root,
      registryFile: registryFile,
      harnessFile: harnessFile,
      metadataFile: metadataFile,
    );
  }

  Future<void> delete() async {
    if (rootDirectory.existsSync()) {
      await rootDirectory.delete(recursive: true);
    }
  }
}

String _registrySource({
  required String packageName,
  required List<DiscoveredPreviewTarget> targets,
}) {
  // Replicate every preview source file's import scope so the verbatim
  // annotations resolve: import each source library itself plus its own import
  // directives, and add the flutter/ambient libraries the registry body needs.
  final importLines = <String>{
    "import 'package:ambient_flutter/ambient_flutter.dart';",
    "import 'package:flutter/widgets.dart';",
    "import 'package:flutter/widget_previews.dart';",
    for (final target in targets) "import '${target.libraryImportUri}';",
    for (final target in targets) ...target.sourceImports,
  }.toList()..sort();

  final buffer = StringBuffer()
    ..writeln('// GENERATED by ambient_flutter. Do not edit.')
    ..writeln(
      '// ignore_for_file: type=lint, unused_import, directives_ordering',
    );
  for (final importLine in importLines) {
    buffer.writeln(importLine);
  }
  buffer
    ..writeln()
    ..writeln(
      'final List<PreviewEntry> ambientGeneratedPreviewEntries = '
      '<PreviewEntry>[',
    );
  for (var index = 0; index < targets.length; index++) {
    final target = targets[index];
    buffer
      ..writeln('  (')
      ..writeln('    annotation: const ${target.annotationSource},')
      ..writeln('    builder: _ambientBuild$index,')
      ..writeln('    targetName: ${jsonEncode(target.targetName)},')
      ..writeln('    sourcePath: ${jsonEncode(target.sourcePath)},')
      ..writeln('    wrapperName: ${jsonEncode(target.wrapperName)},')
      ..writeln('    themeName: ${jsonEncode(target.themeName)},')
      ..writeln(
        '    localizationsName: ${jsonEncode(target.localizationsName)},',
      )
      ..writeln('  ),');
  }
  buffer
    ..writeln('];')
    ..writeln();

  for (var index = 0; index < targets.length; index++) {
    final target = targets[index];
    if (target.returnsWidgetBuilder) {
      buffer
        ..writeln('Widget _ambientBuild$index(BuildContext context) =>')
        ..writeln('    ${target.invocation}(context);')
        ..writeln();
    } else {
      buffer
        ..writeln('Widget _ambientBuild$index(BuildContext context) {')
        ..writeln('  final Object preview = ${target.invocation};')
        ..writeln('  if (preview is Widget) {')
        ..writeln('    return preview;')
        ..writeln('  }')
        ..writeln(
          '  return (preview as Widget Function(BuildContext))(context);',
        )
        ..writeln('}')
        ..writeln();
    }
  }

  return buffer.toString();
}

String _discoveryHarnessSource({
  required String registryImport,
  required String metadataFile,
  required double dpr,
}) {
  return '''
import 'dart:convert';
import 'dart:io';

import 'package:ambient_flutter/ambient_flutter.dart';
import 'package:flutter_test/flutter_test.dart';

import '$registryImport';

void main() {
  TestWidgetsFlutterBinding.ensureInitialized();

  test('discovers ambient previews', () async {
    final previews = describeResolvedPreviews(
      expandAllEntries(ambientGeneratedPreviewEntries),
      dpr: $dpr,
    );
    final file = File(${jsonEncode(metadataFile)});
    await file.create(recursive: true);
    await file.writeAsString(
      jsonEncode(<Map<String, Object?>>[
        for (final preview in previews) preview.toJson(),
      ]),
      flush: true,
    );
  });
}
''';
}

String _captureHarnessSource({
  required String registryImport,
  required String metadataFile,
  required String outputDirectory,
  required double dpr,
}) {
  return '''
import 'dart:convert';
import 'dart:io';
import 'dart:ui' as ui;

import 'package:ambient_flutter/ambient_flutter.dart';
import 'package:flutter/rendering.dart';
import 'package:flutter/widgets.dart';
import 'package:flutter_test/flutter_test.dart';

import '$registryImport';

Future<void> main() async {
  final binding =
      TestWidgetsFlutterBinding.ensureInitialized() as TestWidgetsFlutterBinding;
  final previews = expandAllEntries(ambientGeneratedPreviewEntries);
  final describedPreviews = describeResolvedPreviews(previews, dpr: $dpr);
  final selectedPreviewId = Platform.environment['AMBIENT_PREVIEW_ID'];
  final file = File(${jsonEncode(metadataFile)});
  file.createSync(recursive: true);
  file.writeAsStringSync(
    jsonEncode(<Map<String, Object?>>[
      for (final preview in describedPreviews) preview.toJson(),
    ]),
    flush: true,
  );

  if (selectedPreviewId == null) {
    stderr.writeln('AMBIENT_PREVIEW_ID must be set for capture mode.');
    exit(1);
  }

  final selectedIndex = describedPreviews.indexWhere(
    (preview) => preview.id == selectedPreviewId,
  );
  if (selectedIndex == -1) {
    stderr.writeln('Unknown preview id: \$selectedPreviewId');
    exit(1);
  }

  final preview = previews[selectedIndex];
  final describedPreview = describedPreviews[selectedIndex];
  await loadTestFonts();

  await binding.runTest(() async {
    final size = preview.logicalSize;
    // ignore: deprecated_member_use
    binding.window.devicePixelRatioTestValue = $dpr;
    // ignore: deprecated_member_use
    binding.window.physicalSizeTestValue = size * $dpr;

    final captureKey = GlobalKey();
    binding.attachRootWidget(
      binding.wrapWithDefaultView(
        buildSurface(preview, captureKey: captureKey),
      ),
    );
    binding.scheduleFrame();
    await binding.pump();
    await binding.pump(const Duration(milliseconds: 16));
    await binding.pump(const Duration(milliseconds: 100));

    final boundary =
        captureKey.currentContext!.findRenderObject()! as RenderRepaintBoundary;
    final image = await boundary.toImage(pixelRatio: $dpr);
    final byteData = await image.toByteData(
      format: ui.ImageByteFormat.rawRgba,
    );
    image.dispose();
    final bytes = byteData!.buffer.asUint8List();
    final outputFile = File(
      ${jsonEncode(outputDirectory)} +
          Platform.pathSeparator +
          describedPreview.imagePath +
          '.rgba',
    );
    outputFile.parent.createSync(recursive: true);
    outputFile.writeAsBytesSync(bytes, flush: true);
    // ignore: deprecated_member_use
    binding.window.clearDevicePixelRatioTestValue();
    // ignore: deprecated_member_use
    binding.window.clearPhysicalSizeTestValue();
    exit(0);
  }, () {}, description: 'capture ambient preview');

  throw StateError('Capture harness did not exit after producing the raw output.');
}
''';
}
